"""empty message

Revision ID: 0a50db362e50
Revises: c4b664f23ef3
Create Date: 2020-10-15 22:45:34.724883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a50db362e50'
down_revision = 'c4b664f23ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('servstr', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'servstr')
    # ### end Alembic commands ###
