"""empty message

Revision ID: 0a90b8512d31
Revises: 632da4b36e35
Create Date: 2020-09-18 21:37:40.479913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a90b8512d31'
down_revision = '632da4b36e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agences_entreprise_id_fkey', 'agences', type_='foreignkey')
    op.drop_constraint('agences_create_by_fkey', 'agences', type_='foreignkey')
    op.drop_column('agences', 'entreprise_id')
    op.drop_constraint('entreprises_create_by_fkey', 'entreprises', type_='foreignkey')
    op.drop_constraint('services_agences_id_fkey', 'services', type_='foreignkey')
    op.drop_constraint('services_entreprise_id_fkey', 'services', type_='foreignkey')
    op.drop_column('services', 'agences_id')
    op.drop_column('services', 'entreprise_id')
    op.drop_constraint('tickets_agence_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_entreprise_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_service_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'agence_id')
    op.drop_column('tickets', 'service_id')
    op.drop_column('tickets', 'entreprise_id')
    op.drop_constraint('users_entreprise_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_service_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_agence_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'agence_id')
    op.drop_column('users', 'service_id')
    op.drop_column('users', 'entreprise_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('agence_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_agence_id_fkey', 'users', 'agences', ['agence_id'], ['id'])
    op.create_foreign_key('users_service_id_fkey', 'users', 'services', ['service_id'], ['id'])
    op.create_foreign_key('users_entreprise_id_fkey', 'users', 'entreprises', ['entreprise_id'], ['id'])
    op.add_column('tickets', sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('agence_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tickets_service_id_fkey', 'tickets', 'services', ['service_id'], ['id'])
    op.create_foreign_key('tickets_entreprise_id_fkey', 'tickets', 'entreprises', ['entreprise_id'], ['id'])
    op.create_foreign_key('tickets_agence_id_fkey', 'tickets', 'agences', ['agence_id'], ['id'])
    op.add_column('services', sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('agences_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('services_entreprise_id_fkey', 'services', 'entreprises', ['entreprise_id'], ['id'])
    op.create_foreign_key('services_agences_id_fkey', 'services', 'agences', ['agences_id'], ['id'])
    op.create_foreign_key('entreprises_create_by_fkey', 'entreprises', 'users', ['create_by'], ['id'])
    op.add_column('agences', sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('agences_create_by_fkey', 'agences', 'users', ['create_by'], ['id'])
    op.create_foreign_key('agences_entreprise_id_fkey', 'agences', 'entreprises', ['entreprise_id'], ['id'])
    # ### end Alembic commands ###
