"""empty message

Revision ID: 21347270e142
Revises: 0a90b8512d31
Create Date: 2020-09-18 21:58:47.589226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21347270e142'
down_revision = '0a90b8512d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entreprises', 'users', ['create_by'], ['id'])
    op.add_column('users', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'entreprises', ['entreprise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'entreprise_id')
    op.drop_constraint(None, 'entreprises', type_='foreignkey')
    # ### end Alembic commands ###
