"""empty message

Revision ID: 2fbf33e12e4c
Revises: 9b7357117913
Create Date: 2020-11-01 06:59:07.828910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbf33e12e4c'
down_revision = '9b7357117913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_token')
    # ### end Alembic commands ###
