"""empty message

Revision ID: 337b91edf68b
Revises: 4c26ce9196e9
Create Date: 2020-09-11 13:53:26.915094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337b91edf68b'
down_revision = '4c26ce9196e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
