"""empty message

Revision ID: 469c21f67df4
Revises: b7b0ed32717a
Create Date: 2020-07-31 01:15:45.515870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469c21f67df4'
down_revision = 'b7b0ed32717a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agences', 'modify_by')
    op.drop_column('entreprises', 'modify_by')
    op.drop_column('services', 'modify_by')
    op.drop_column('tickets', 'modify_by')
    op.drop_column('users', 'modify_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('modify_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('modify_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('modify_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('entreprises', sa.Column('modify_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agences', sa.Column('modify_by', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
