"""empty message

Revision ID: 4c26ce9196e9
Revises: 2a1a46d26e0e
Create Date: 2020-09-11 13:51:32.501155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c26ce9196e9'
down_revision = '2a1a46d26e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
