"""empty message

Revision ID: 58ef7e565ff5
Revises: ed25d9e54c44
Create Date: 2020-10-30 05:02:57.714921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ef7e565ff5'
down_revision = 'ed25d9e54c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprises', sa.Column('state', sa.Boolean(), nullable=True))
    op.drop_column('users', 'google')
    op.drop_column('users', 'facebook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('entreprises', 'state')
    # ### end Alembic commands ###
