"""empty message

Revision ID: 70ce3b91ade3
Revises: 7bf5d16a4a62
Create Date: 2020-07-31 01:31:56.601714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ce3b91ade3'
down_revision = '7bf5d16a4a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprises', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entreprises', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entreprises', type_='foreignkey')
    op.drop_column('entreprises', 'user_id')
    # ### end Alembic commands ###
