"""empty message

Revision ID: 7bf5d16a4a62
Revises: 04d0b8d4ce33
Create Date: 2020-07-31 01:21:16.658983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf5d16a4a62'
down_revision = '04d0b8d4ce33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agences', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agences', type_='foreignkey')
    op.drop_column('agences', 'user_id')
    # ### end Alembic commands ###
