"""empty message

Revision ID: 8742ab702801
Revises: b34145008dc1
Create Date: 2020-09-27 11:25:48.752131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8742ab702801'
down_revision = 'b34145008dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guichets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_modify', sa.DateTime(), nullable=True),
    sa.Column('modify_by', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('agences_id', sa.Integer(), nullable=True),
    sa.Column('services_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agences_id'], ['agences.id'], ),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.ForeignKeyConstraint(['services_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('guichet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'guichets', ['guichet_id'], ['id'])
    op.add_column('users', sa.Column('guichet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'guichets', ['guichet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'guichet_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'guichet_id')
    op.drop_table('guichets')
    # ### end Alembic commands ###
