"""empty message

Revision ID: 9b7357117913
Revises: 58ef7e565ff5
Create Date: 2020-10-30 06:30:15.043755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7357117913'
down_revision = '58ef7e565ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprises', sa.Column('logo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprises', 'logo')
    # ### end Alembic commands ###
