"""empty message

Revision ID: 9c214e4ea954
Revises: 3fe1eb7309b5
Create Date: 2020-09-18 20:27:17.091905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c214e4ea954'
down_revision = '3fe1eb7309b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agences_user_id_fkey', 'agences', type_='foreignkey')
    op.create_foreign_key(None, 'agences', 'users', ['create_by'], ['id'])
    op.drop_column('agences', 'user_id')
    op.drop_constraint('entreprises_user_id_fkey', 'entreprises', type_='foreignkey')
    op.create_foreign_key(None, 'entreprises', 'users', ['create_by'], ['id'])
    op.drop_column('entreprises', 'user_id')
    op.add_column('users', sa.Column('agence_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'users', 'entreprises', ['entreprise_id'], ['id'])
    op.create_foreign_key(None, 'users', 'agences', ['agence_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'service_id')
    op.drop_column('users', 'entreprise_id')
    op.drop_column('users', 'agence_id')
    op.add_column('entreprises', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'entreprises', type_='foreignkey')
    op.create_foreign_key('entreprises_user_id_fkey', 'entreprises', 'users', ['user_id'], ['id'])
    op.add_column('agences', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agences', type_='foreignkey')
    op.create_foreign_key('agences_user_id_fkey', 'agences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
