"""empty message

Revision ID: b34145008dc1
Revises: f50d16c15e53
Create Date: 2020-09-18 22:06:30.921262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34145008dc1'
down_revision = 'f50d16c15e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('agences_id', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'users', ['create_by'], ['id'])
    op.create_foreign_key(None, 'services', 'agences', ['agences_id'], ['id'])
    op.create_foreign_key(None, 'services', 'entreprises', ['entreprise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'entreprise_id')
    op.drop_column('services', 'agences_id')
    # ### end Alembic commands ###
