"""empty message

Revision ID: b7b0ed32717a
Revises: fdeedf8b68ad
Create Date: 2020-07-31 00:35:35.128266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b0ed32717a'
down_revision = 'fdeedf8b68ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agences', sa.Column('code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agences', 'code')
    # ### end Alembic commands ###
