"""empty message

Revision ID: c4b664f23ef3
Revises: fdb3657a7e8d
Create Date: 2020-09-29 03:33:10.036676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b664f23ef3'
down_revision = 'fdb3657a7e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agences', sa.Column('logo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agences', 'logo')
    # ### end Alembic commands ###
