"""empty message

Revision ID: cf6600984258
Revises: 9c214e4ea954
Create Date: 2020-09-18 20:50:32.044157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6600984258'
down_revision = '9c214e4ea954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google')
    op.drop_column('users', 'facebook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
