"""empty message

Revision ID: ed25d9e54c44
Revises: 0a50db362e50
Create Date: 2020-10-29 03:53:35.214560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed25d9e54c44'
down_revision = '0a50db362e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_guichet_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_service_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_agence_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'guichet_id')
    op.drop_column('users', 'service_id')
    op.drop_column('users', 'agence_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agence_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('guichet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_agence_id_fkey', 'users', 'agences', ['agence_id'], ['id'])
    op.create_foreign_key('users_service_id_fkey', 'users', 'services', ['service_id'], ['id'])
    op.create_foreign_key('users_guichet_id_fkey', 'users', 'guichets', ['guichet_id'], ['id'])
    # ### end Alembic commands ###
