"""empty message

Revision ID: f50d16c15e53
Revises: 21347270e142
Create Date: 2020-09-18 22:02:32.431027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50d16c15e53'
down_revision = '21347270e142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agences', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agences', 'entreprises', ['entreprise_id'], ['id'])
    op.create_foreign_key(None, 'agences', 'users', ['create_by'], ['id'])
    op.add_column('tickets', sa.Column('agence_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'agences', ['agence_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'entreprises', ['entreprise_id'], ['id'])
    op.add_column('users', sa.Column('agence_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'users', 'agences', ['agence_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'service_id')
    op.drop_column('users', 'agence_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'service_id')
    op.drop_column('tickets', 'entreprise_id')
    op.drop_column('tickets', 'agence_id')
    op.drop_constraint(None, 'agences', type_='foreignkey')
    op.drop_constraint(None, 'agences', type_='foreignkey')
    op.drop_column('agences', 'entreprise_id')
    # ### end Alembic commands ###
