"""empty message

Revision ID: fdb3657a7e8d
Revises: 8742ab702801
Create Date: 2020-09-28 21:15:15.637963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb3657a7e8d'
down_revision = '8742ab702801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_modify', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('modify_by', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=64), nullable=True),
    sa.Column('etat', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=255), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('agence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agence_id'], ['agences.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicites')
    # ### end Alembic commands ###
