"""empty message

Revision ID: fdeedf8b68ad
Revises: 1071c04b477f
Create Date: 2020-07-30 15:11:07.419514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdeedf8b68ad'
down_revision = '1071c04b477f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agences', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agences', 'entreprises', ['entreprise_id'], ['id'])
    op.add_column('services', sa.Column('agences_id', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'entreprises', ['entreprise_id'], ['id'])
    op.create_foreign_key(None, 'services', 'agences', ['agences_id'], ['id'])
    op.add_column('tickets', sa.Column('agence_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'agences', ['agence_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'entreprises', ['entreprise_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'service_id')
    op.drop_column('tickets', 'entreprise_id')
    op.drop_column('tickets', 'agence_id')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'entreprise_id')
    op.drop_column('services', 'agences_id')
    op.drop_constraint(None, 'agences', type_='foreignkey')
    op.drop_column('agences', 'entreprise_id')
    # ### end Alembic commands ###
